name: Workflow for push on master version of Coq

on:
  push:
    branches:
      - coq-master

jobs:
  from-sources:
    uses: ./.github/workflows/from-sources.yml
    with:
      image-version: ${{ github.ref_name }}
